# =============================================================================
# INVENTORY - hosts.yml
# =============================================================================

---
all:
  children:
    app:
      hosts:
        app1:
          ansible_host: 54.86.30.170
        app2:
          ansible_host: 3.231.53.84
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/capstone-key.pem
